[tools]
golang = { version = 'latest' }
python = { version = 'latest' }
java = 'openjdk'
grpcurl = 'latest'
shfmt = 'latest'
shellcheck = '0.9.0'
ripgrep = 'latest'
awscli = 'latest'
zoxide = 'latest'
starship = 'latest'
fzf = 'latest'
jq = 'latest'
assh = 'latest'
direnv = 'latest'

[settings]
verbose = false
yes = true
legacy_version_file = false
experimental = true

[settings.status]
show_tools = true
show_env = true
