[tools]
golang = { version = 'latest' }
python = { version = 'latest' }
java = 'adoptopenjdk-17'
grpcurl = 'latest'
shfmt = 'latest'
shellcheck = '0.9.0'
ripgrep = 'latest'
awscli = 'latest'
zoxide = 'latest'
starship = 'latest'
fzf = 'latest'
jq = 'latest'

[settings]
verbose = true
yes = true
legacy_version_file = false
