[tools]
golang = { version = 'latest' }
python = { version = 'latest' }
java = 'openjdk'
grpcurl = 'latest'
shfmt = 'latest'
shellcheck = 'latest'

[settings]
verbose = false
yes = true
legacy_version_file = false
experimental = true

[settings.status]
show_tools = true
show_env = true
